// packages/next/playground/app/docs/[slug]/page.tsx
import { PrecogLink as Link } from "next-precog";
import { DOC_SLUGS, docBody, docTitle } from "../../docs";

export function generateStaticParams() {
  return DOC_SLUGS.map((slug) => ({ slug }));
}

export default async function Doc({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const others = DOC_SLUGS.filter((other) => other !== slug).slice(0, 6);

  return (
    <main>
      <h1>{docTitle(slug)}</h1>
      {docBody(slug).map((paragraph, index) => (
        <p key={index}>{paragraph}</p>
      ))}
      <h2>See also</h2>
      <ul>
        {others.map((other) => (
          <li key={other}>
            <Link href={`/docs/${other}`}>{docTitle(other)}</Link>
          </li>
        ))}
      </ul>
      <Link href="/docs">Back to the docs</Link>
    </main>
  );
}

// packages/nuxt/playground/pages/docs/[slug].vue
<script setup lang="ts">
import { DOC_SLUGS, docBody, docTitle } from "#shared/docs";

const route = useRoute();
const slug = computed(() => String(route.params.slug));
const { data } = await useAsyncData(
  () => `doc-${slug.value}`,
  () => Promise.resolve({ title: docTitle(slug.value), body: docBody(slug.value) }),
  { watch: [slug] },
);
const others = computed(() => DOC_SLUGS.filter((other) => other !== slug.value).slice(0, 6));
</script>

<template>
  <main>
    <h1>{{ data?.title }}</h1>
    <p v-for="(paragraph, index) in data?.body" :key="index">{{ paragraph }}</p>
    <h2>See also</h2>
    <ul>
      <li v-for="other in others" :key="other">
        <NuxtLink :to="`/docs/${other}`">{{ docTitle(other) }}</NuxtLink>
      </li>
    </ul>
    <NuxtLink to="/docs">Back to the docs</NuxtLink>
  </main>
</template>
