// packages/next/playground/app/docs/page.tsx
import { PrecogLink as Link } from "@precog/next";
import { DOC_SLUGS, docTitle } from "../docs";

export default function Docs() {
  return (
    <main>
      <h1>Docs</h1>
      <p>Every page here is rendered at build time, so it has an RSC payload to warm up.</p>
      <ul>
        {DOC_SLUGS.map((slug) => (
          <li key={slug}>
            <Link href={`/docs/${slug}`}>{docTitle(slug)}</Link>
          </li>
        ))}
      </ul>
    </main>
  );
}

// playground/pages/docs/index.vue
<script setup lang="ts">
import { DOC_SLUGS, docTitle } from "../../shared/docs";
</script>

<template>
  <main>
    <h1>Docs</h1>
    <p>Every page here is prerendered, so it has a payload the module can warm up.</p>
    <ul>
      <li v-for="slug in DOC_SLUGS" :key="slug">
        <NuxtLink :to="`/docs/${slug}`">{{ docTitle(slug) }}</NuxtLink>
      </li>
    </ul>
  </main>
</template>
